TIPSTER_SOURCES = {
    'HKJC': [
        'Paul Lally',
        'Tom Wood',
        'Jenny Chapman',
        'Nick Child',
        'Mark McNamara',
        'Andrew Le Jeune',
        'Alan Aitken',
    ],
    'KinBoy': [
        'Jacky',
        'Windson',
        'Baron',
        'Anthony',
        'Oscar',
        'KC',
    ],
    'Newspaper': [
        'iRace',
        'Daily',
        'HKDN',
        'Sun Journal',
        'Today Jockey',
    ],
    'racing.on.cc': [
        '張基',
        '卡洛斯',
        '匡公',
        '金駒',
        '西門獨',
        '諸葛數',
        '長風',
        '蔡俊佳',
        '陳志懷',
        '明治朗',
    ],
}
